export const MOVIETYPES = {
   GET_SHOWS: 'GET_SHOWS',
   GET_EPISODES: 'GET_EPISODES',
   SEARCH_SHOWS: 'SEARCH_SHOWS',
   GET_CAST: 'GET_CAST',
   SET_LOADING: 'SET_LOADING',
   SET_ERROR: 'SET_ERROR',
   SET_NOT_FOUND: 'SET_NOT_FOUND',
   REMOVE_NOT_FOUND: 'REMOVE_NOT_FOUND'
};
